version: '3.7'

networks:
  my-network:

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
      MYSQL_USER: todosuser
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my-network

  api:
    build: ./backend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
      MYSQL_USER: todosuser
      MYSQL_PASSWORD: password
      HOST: db
      PORT: 3306
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - my-network
  frontend:
    build: ./frontend
    ports:
      - '8081:80'
    depends_on:
      - api
    networks:
      - my-network

volumes:
  data: